demo: # Replace with a *short* name that can identify your model in code/URLs. Use only lower-case letters or hyphens.
  name: Demo Model # Name of your model, to be displayed in the UI
  origin: Covid Policy Modelling # Name of the organisation responsible for the model, to be displayed in the UI
  enabled: true # Set to false if your repository is private
  imageURL: docker.pkg.github.com/covid-policy-modelling/model-connector-template/model-connector:latest # URL of your published Docker container
  metaURLs: # (Optional) URLs with more data about the model, to be displayed in the UI
    code: https://github.com/covid-policy-modelling/model-connector-template
    paper: https://github.com/covid-modeling/covid-model-evaluation/blob/main/how-predictive-are-models-of-covid-19.pdf
    website: https://github.com/covid-policy-modelling
  description: |
    A template for adding new models
    A short description of your model, around a paragraph, to be displayed in the UI
  supportedParameters: # Delete parameters (as supplied in the input schema) that your model connector does not support
    - interventionStrategies
    - contactReduction
    - r0
  supportedRegions: # List regions and subregions (as described in the input schema) that your model connector supports
    GB:
      - GB-ENG
      - GB-NIR
      - GB-SCT
      - GB-WAL
    US:
      - US # If the connector supports both the top-level region and some subregions, you must explicitly repeat the top-level region in the array
      - US-AK
      - UK-AL
    IE: # As a convenience, you can use a missing value if the connector only supports the top-level region
    CA: [] # Or an empty array
