name: Connector - Publish Docker Image for Tags/Releases
on:
  push:
    # Publish `v1.2.3` tags as Docker package versions.
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,refs/\(heads\|tags\)/\(.*\),\2,' | tr '/' '-')
          # Strip "refs/tags/v" prefix from tag name
          [[ "${GITHUB_REF}" == "refs/tags/"* ]] && VERSION=$(echo "${GITHUB_REF}" | sed -e 's:^refs/tags/v::')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build image
        # Name it `image` for now. The push step below will set a meaningful name.
        run: docker build --build-arg CONNECTOR_VERSION=$VERSION -t image -f Docker/Dockerfile .

      - name: Log into package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Tag and push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${GITHUB_REPOSITORY}/model-connector
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Tag with the version number that remains in the tag name
          echo IMAGE_ID=${IMAGE_ID}
          echo VERSION=${VERSION}
          docker tag image ${IMAGE_ID}:${VERSION}
          docker push ${IMAGE_ID}:${VERSION}
